data:
  data_dir: data
  hf_dataset_name: akalmbach-kinsol/generative-papers-arxiv
  citations_batch_size: 10000
  basemodel_name: sentence-transformers/allenai-specter
  embedding_batch_size: 5000
  test_size: 0.1
  random_seed: 42
  max_length: 256
  pad_to_multiple_of: 8
  pad_value: 0.0
model:
  hidden_size: 768
  num_hidden_layers: 1
  num_attention_heads: 12
  intermediate_size: 1536
  max_position_embeddings: 2048
training:
  batch_size: 256
  num_workers: 6
  num_epochs: 20
  learning_rate: 0.001
  log_steps: 10
  save_steps: 500
  tensorboard_dir: runs
evaluation:
  batch_size: 256
  num_workers: 0
  max_batches: 10
rectflow:
  velocity_field_type: DiT
  num_blocks: 1
  num_heads: 4
  mlp_ratio: 4.0
  conditioning_checkpoint: null
rectflow_training:
  batch_size: 128
  num_workers: 6
  num_epochs: 100
  learning_rate: 0.0002
  train_time_weight: uniform
  train_time_distribution: lognormal
  log_steps: 10
  save_steps: 500
  tensorboard_dir: runs_rectflow
